### ISSUE TITLE
Problem converting Illumina Genome reports to vcf 

### ISSUE THREAD

**Issue by vikrantsingh1** [freeseek/gtc2vcf#1]
Hi, 
Thank you for the wonderful set of tool for converting the illumina reports to vcf files.

I am getting a error while using the matrix format illumina reports.

Error is as follows:

./bcftools +gtc2vcf.so --no-version -o --genome-studio /Users/vikrants/Desktop/testvcf/ILHC24-12806_FinalReport.txt -f /Users/vikrants/res/hg38.fa 
================================================================================
Reading GTC file /Users/vikrants/Desktop/testvcf/ILHC24-12806_FinalReport.txt
GTC file /Users/vikrants/Desktop/testvcf/ILHC24-12806_FinalReport.txt format identifier is bad

Can you please have a look and let me know why i am getting this error.

P.S. - I have generated the matrix format report from the genome studio.

Thanks in advance,
Vikrant

**Comment by freeseek** [comment]
Option "-o" needs a "<file>" parameter. Try that.

**Comment by vikrantsingh1** [comment]
Thank you so much for the reply.
After adding the parameter with -o. I am getting another error. 

./bcftools +gtc2vcf.so --no-version -Ov --genome-studio /Users/vikrants/Desktop/testvcf/ILHC24-12806_FinalReport.txt -f /Users/vikrants/res/hg38.fa 

Could not recognize INFO field: [Header]

**Comment by freeseek** [comment]
There is no information about BAF, LRR, chromosome number, what alleles are TOP or BOT or alternatively what the reference strand is. You just can't make a VCF out of that. I would advise you to go back to the GTC files here, if you can. I will add some information in the documentation about what the file should look like. Thank you for your feedback.

**Comment by vikrantsingh1** [comment]
Thank you so much for sharing the example for matrix format.

I able to convert the files into vcf files.

Thanks and Regards,
Vikrant

**Comment by SeqSii** [comment]
Dear freeseek,
thank you for your tool!
I wonder if you could also share the example for the matrix format with me!?
I'm asking because in GenomeStudio2 (GS2) you can either choose to export a FinalReport in matrix format which basically only has all samples in the columns and var's in rows (see vikrant's post above) with no further options to change/add
OR
you export a standard FinalReport where you can show and hide different columns.

With both variants you'll get the GS2 header which BCFtools can't handle - at least the [Header] and [Data]... When you get rid of this it still expects some INFO tags/column names like CHROM, SNP...
This is a recent example from an export:

[Header]
GSGT Version	2.0.4
Processing Date	9/17/2019 10:46 AM
Content		sub_GSAMD-24v2-0_20024620_A1.bpm
Num SNPs	738923
Total SNPs	759993
Num Samples	5
Total Samples	1006
[Data]
Chr	Position	ILMN Strand	SNP	SNP Name	Allele1 - AB	Allele2 - AB	GT Score	Theta	R	B Allele Freq	Log R Ratio
1	100292476	TOP	[A/G]	1:100292476	A	A	0.6636	0.229	0.798	0.0000	0.0142
1	101064936	TOP	[A/G]	1:101064936	A	A	0.6628	0.146	3.024	0.0000	-0.0018
1	103380393	BOT	[T/C]	1:103380393	B	B	0.8444	0.975	0.877	1.0000	0.0590

As you can see GS2 has different names for the columns compared to your example in your README.md. I chose AB alleles according to your example...

When I run the command it returns 'Expected CHROM column'
I would like to know now the exact column names to use it with your tool,
if I have to export AB alleles and remove the TAB between the two OR if it also works with Top alleles,
and if the GS2 exported FinalReport can also include other information than you show in your example?

I really would like to use your tool to convert other FinalReport's which I have in place but without having .idats or .gts's.

Thank you in advance,
Sagi

**Comment by freeseek** [comment]
Dear sagi,
The tutorial for gtc2vcf does contains an example of what a GS final report should look like. What you are showing me does not look like matrix format. Unfortunately I have seen this issue before and it would require a completely different and non-memory efficient code to parse such a GS final report. I would advise to not use GenomeStudio and software from Illumina wherever possible. The pipeline I provided from IDATs or GTCs should work just fine.

**Comment by SeqSii** [comment]
Dear Giulio,
thanks for your swift answer.

It works just fine from the other formats but unfortunately it is very hard
to get IDAT's or GTC's from others!
Mostly they provide Plink1 binaries - which is completely outdated - or
they provide an Illumina FinalReport with either TOP or AB alleles
extracted.
I'll give it a last try to create a Final Report with samples in the
columns but the Illumina 'function' matrix definitely doesn't work at least
out of the box.

Many thanks anyways.
Best,
Sagi

**Comment by mczajk83** [comment]
Dear @freeseek,

My problem is similar to @SeqSii ..
Currently I've got over 5000 samples in a GenomeStudio2 (GS2) project. All I can do is  
- extract final report just like @SeqSii which does not fit to gthc2vcf
- extract other report that can be used for PLINK CNV analysis
- use plink plugin to export the data to ped/map and then to bim/bed/fam or later to vcf but without ALLELE_A, ALLELE_B, GC, GT, BAF, and LRR information

Is there any way I get get the desired vcf that can later fit to MoCha? 

Best,
Marcin

**Comment by freeseek** [comment]
In general, gtc2vcf will be able to convert GenomeStudio final report tables as long as they are structured in matrix format with multiple samples on each row. Some final reports are structured in a way that data for each sample is reported as a single block. The latter format cannot be converted to VCF as a stream and therefore it would require quite a different architecture to be converted. The former format instead should work with `--genome-studio`. However, there is no specification from Illumina for how the tables are structured, so there is no guarantee it will actually work. If you have a table in matrix format that does not convert correctly, reach out to me with an example and we can get it sorted out. My best advice is still to do the right thing, and demand that the data provider gives you with the raw data, i.e. the IDAT files. Data providers need to understand the importance of raw data for scientific reproducibility.

**Comment by mczajk83** [comment]
Thanks @freeseek  for such fast response. In GenomeStudio2 I can generate like @SeqSii  either final raport in a matrix form without any possibility of configuration: header is like this: 
----------------------------------
[Header]
GSGT Version	2.0.4
Processing Date	5/10/2021 10:50 AM
Content		GSA-24v3-0_A2.bpm
Num SNPs	654027
Total SNPs	654027
Num Samples	5
Total Samples	5192
[Data]
	BAT0001	BAT0002	BAT0003	BAT0004	BAT0005
1:103380393	AG|0.8136	GG|0.8136	AG|0.8136	GG|0.8136	GG|0.8136
1:109439680	AA|0.4803	AA|0.4803	AA|0.4803	AA|0.4803	AA|0.4803
1:110198788	AA|0.9154	AA|0.9154	AA|0.9154	AA|0.9154	AA|0.9154
-------------------------------------

either I can extract final row based (sorted by sample or SNP Name)  with much more columns which I can configure but not in a matrix form. Here is an output with all possible columns
a) by SNP
[Header]
GSGT Version	2.0.4
Processing Date	5/10/2021 10:48 PM
Content		GSA-24v3-0_A2.bpm
Num SNPs	654027
Total SNPs	654027
Num Samples	5
Total Samples	5192
[Data]
Chr	Position	ILMN Strand	SNP	Sample Name	SNP Name	Sample Group	GC Score	GT Score	Theta	R	B Allele Freq	Log R Ratio	X	Plus/Minus Strand	Y	X Raw	Y Raw	Top Genomic Sequence	CNV Value	Customer Strand	CNV Confidence	Cluster Sep	Allele1 - Plus	Allele2 - AB	Allele1 - AB	Allele2 - Design	Allele1 - Design	Allele2 - Forward	Allele2 - Plus	Sample ID	Allele1 - Top	Allele1 - Forward	Allele2 - Top	SNP Aux	SNP Index	Sample Index
1	102914837	BOT	[T/C]	BAT0001	1:103380393		0.8136	0.7987	0.972	0.718	1.0000	0.3528	0.030	-	0.688	470	2847			TOP		0.4964	G	B	B	C	C	G	G	BAT 6 / V2	G	G	G	0	1	2
1	102914837	BOT	[T/C]	BAT0002	1:103380393		0.8136	0.7987	0.985	0.695	1.0000	0.3045	0.016	-	0.679	287	3010			TOP		0.4964	G	B	B	C	C	G	G	BAT 10 / V2	G	G	G	0	1	4

-------------------------------------
b) by sample: 
[Header]
GSGT Version	2.0.4
Processing Date	5/10/2021 11:02 AM
Content		GSA-24v3-0_A2.bpm
Num SNPs	654027
Total SNPs	654027
Num Samples	5
Total Samples	5192
[Data]
Chr	Position	ILMN Strand	SNP	Sample Name	SNP Name	Sample Group	GC Score	GT Score	Theta	R	B Allele Freq	Log R Ratio	X	Plus/Minus Strand	Y	X Raw	Y Raw	Top Genomic Sequence	CNV Value	Customer Strand	CNV Confidence	Cluster Sep	Allele1 - Plus	Allele2 - AB	Allele1 - AB	Allele2 - Design	Allele1 - Design	Allele2 - Forward	Allele2 - Plus	Sample ID	Allele1 - Top	Allele1 - Forward	Allele2 - Top	SNP Aux	SNP Index	Sample Index
1	102914837	BOT	[T/C]	BAT0001	1:103380393		0.8136	0.7987	0.490	0.815	0.4414	0.5769	0.414	-	0.402	4246	1908			TOP		0.4964	A	B	A	C	T	G	G	BAT 4 / V2	A	A	G	0	1	1
1	108897058	TOP	[A/G]	BAT0001	1:109439680		0.4803	0.8792	0.008	0.726	0.0000	0.1346	0.717	+	0.009	6205	96			TOP		1.0000	A	A	A	A	A	A	A	BAT 4 / V2	A	A	A	0	2	1
1	109656166	BOT	[T/C]	BAT0001	1:110198788		0.9154	0.8780	0.033	1.198	0.0066	0.0198	1.138	+	0.060	12901	428			BOT		1.0000	T	A	A	T	T	T	T	BAT 4 / V2	A	T	A	0	3	1
1

-------------------------------------

I think I could write some python script to format these row-based file into a matrix one but I would need from you an example how the output file (final report) should look like and what column names should I use (as there are differences as @SeqSii  pointed out). 

Thanks,
Marcin

**Comment by freeseek** [comment]
The formats you are showing will not work. It should look something like this:
```
Chromosome      Position        IlmnStrand      SNP     Name    SM.GType        SM.Score        SM.Theta        SM.R    SM.B Allele Freq        SM.Log R Ratio
9       139906359       BOT     [T/C]   200003  AA      0.9299  0.029   1.300   0.0027  0.2150
9       139926402       TOP     [A/G]   200006  AB      0.7877  0.435   2.675   0.4742  0.3024
2       220084902       BOT     [T/C]   200047  AA      0.8612  0.083   0.476   0.0532  -0.1173
2       220089685       TOP     [C/G]   200050  BB      0.8331  0.995   1.499   1.0000  0.3068
```
Where `SM` is the sample name and you could have additional columns with data for other samples. There should be a way to output a table like this with GenomeStudio. But I have never used the software. Let me know if you figure it out.

**Comment by mczajk83** [comment]
So in each line we have fixed:
Chromosome      Position        IlmnStrand      SNP    
and then next columns 7 are for each sample:
Name (**as sample name ? or is it SNP name?**)    SM.GType        SM.Score        SM.Theta        SM.R    SM.B Allele Freq        SM.Log R Ratio [new sample] Name  SM.GType        SM.Score        SM.Theta        SM.R    SM.B Allele Freq        SM.Log R Ratio .... 

so e.g. for 100 samples we have 4 fixed columns and exactly 7*100 columns with samples data?  If you could paste real example with more than 1 sample it would be great

And final question how do you create  GType ? Can I use like @SeqSii  as added columns Allele1 - AB with Allele2 - AB ? (there are also colums like Allele1 - Plus ; Allele2 - Design ; Allele1 - Design	; Allele2 - Forward	; Allele2 - Plus	; Allele1 - Top	; Allele1 - Forward	; Allele2 - Top) 

As I mentioned, I think I will just script it so the output will fit yours and then maybe it will work :) 

Thanks,
Marcin

**Comment by freeseek** [comment]
That's correct but make sure the table is tab delimited (rather than space delimited). Again, I have never used GenomeStudio, but if you are able to open this dataset as a project, there must be a way to output the data in a format that can be input in gtc2vcf. Maybe it is not "matrix format" and maybe it has another name. You should not have to do this manually. If you have any further feedback to help other users let me know.
