### ISSUE TITLE
IDAT to GTC not working

### ISSUE THREAD

**Issue by robertosirica** [freeseek/gtc2vcf#10]
Hello, I tried to obtain gtc files from idat using the command line in the tutorial :

`mono $HOME/bin/autoconvert/AutoConvert.exe $path_to_idat_folder $path_to_output_folder $manifest_file $egt_file`

unfortunately the process gives me, as you said, the normalization error. I tried to use a custom cluster file and a custom manifest file with a ".csv" extension, could it be possible that the error raises because of this. For me it's mandatory to use custom egt and csv or bpm files because of some added SNPs is there a solution to this issue? 

Thank you

**Comment by freeseek** [comment]
Usually that means you are not using the correct BPM or EGT file. Sometimes I have seen some IDATs where normalization will just fail and they cannot be recovered.

You can peek at the IDATs and manifest files with this
```
bcftools +gtc2vcf -i xxx.idat
bcftools +gtc2vcf -b xxx.bpm
bcftools +gtc2vcf -e xxx.egt
```
And it will tell you how many entries are in each file. Those numbers should be close but they don't need to be the same. I don't know a way to figure out what pair of BPM and EGT files you should be using for a given pair of Green and Red IDATs.
