### ISSUE TITLE
[E::bcf_hdr_read] Input is not detected as bcf or vcf format

### ISSUE THREAD

**Issue by aleshchyk** [freeseek/gtc2vcf#13]
Hello,

when I try to convert .gtc files to .vcf I get the error "[E::bcf_hdr_read] Input is not detected as bcf or vcf format". It seems like the .gtc header size is bigger than expected. Can you please help me to fix this error?

Thank you.

**Comment by freeseek** [comment]
It would be helpful to know what command you have run. I am guessing you are piping one bcftools command into another bcftools command. Try running only the first command to see what error you get.

**Comment by aleshchyk** [comment]
I get the error when I convert Illumina GTC files to VCF with this code:

bpm_manifest_file="..."
csv_manifest_file="..."
egt_cluster_file="..."
gtc_list_file="..."
ref="$HOME/res/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna" # or ref="$HOME/res/human_g1k_v37.fasta"
out_prefix="..."
bcftools +gtc2vcf \
  --no-version -Ou \
  -b $bpm_manifest_file \
  -c $csv_manifest_file \
  -e $egt_cluster_file \
  -g $gtc_list_file \
  -f $ref \
  -x $out_prefix.sex | \
  bcftools sort -Ou -T ./bcftools-sort.XXXXXX | \
  bcftools norm --no-version -Ob -o $out_prefix.bcf -c x -f $ref && \
  bcftools index -f $out_prefix.bcf

The error:
Failed to read from file path/gtc_610/
[E::bcf_hdr_read] Input is not detected as bcf or vcf format
Could not read VCF/BCF headers from -
Cleaning
Failed to read from standard input: unknown file type

**Comment by freeseek** [comment]
path/gtc_610/ is not a file, it is a directory. The error is spelled out there for you. You are trying to feed something that is not a file while it should be a file.

**Comment by aleshchyk** [comment]
The description says " You can use gtc2vcf to convert one GTC file at a time, but we strongly advise to convert multiple files at once as single sample VCF files will consume a lot of storage space." I put a path to a folder with multiple gtc files assuming it will work. Can you please suggest a way how to convert multiple gtc files into a single vcf? Thank you

**Comment by freeseek** [comment]
You need to make a file with the list of all .gtc files you want to convert at once and pass that with the -g option. I might add the feature you suggested tomorrow, it should be easy to implement.

**Comment by aleshchyk** [comment]
It worked, thank you!

**Comment by freeseek** [comment]
I have changed the code and now with the --gtcs option you can pass either a directory with GTC files inside or a file with a list of GTC files.
