### ISSUE TITLE
Issue "Reading EGT file: Data block version 5 in cluster file not supported"

### ISSUE THREAD

**Issue by aleshchyk** [freeseek/gtc2vcf#14]
Hello,

after I obtained gtc files from idat files using Human CVN 370 manifest (.egt and .bpm files), I ran this code to get vcf file:
 
source /software/bcftools/1.9/start_bcftools.sh
bpm_manifest_file="humancnv370v1_c.bpm"
egt_cluster_file="HumanCNV370v1_C.egt"
gtc_list_file="gtc_370.txt"
ref="human_g1k_v37.fasta"
out_prefix="X"
bcftools +gtc2vcf \
  --no-version -Ov \
  -b $bpm_manifest_file \
  -e $egt_cluster_file \
  -g $gtc_list_file \
  -f $ref \
  -x $out_prefix.sex | \
  bcftools sort -Ov -T ./bcftools-sort.XXXXXX | \
  bcftools norm --no-version -Ov -o $out_prefix.vcf -c x -f $ref && \
  bcftools index -f $out_prefix.vcf

I get the following error: 
Reading EGT file HumanCNV370v1_C.egt
Data block version 5 in cluster file not supported
[E::bcf_hdr_read] Input is not detected as bcf or vcf format
Could not read VCF/BCF headers from -
Cleaning
Failed to read from standard input: unknown file type

Can you please help me with this?

Thank you.

**Comment by freeseek** [comment]
Hmmm. I just checked the cluster file from https://support.illumina.com/downloads/humancnv370-duo_v10_product_files.html and indeed the data block version, the way the data is stored in the egt file, is 5 but only versions 7, 8, and 9 are supported. Illumina does not share the specifications so this would need to be reverse engineered to make gtc2vcf compatible with version 5.

**Comment by freeseek** [comment]
It turned out it was an easy fix. Can you recompile the new version of the code and see if works for you now?
