### ISSUE TITLE
Can't open .xcl.bcf file

### ISSUE THREAD

**Issue by aleshchyk** [freeseek/gtc2vcf#15]
Hello,

I got the .xcl.bcf file after this step:

/bcftools  annotate --no-version -Ob -o $pfx.unphased.bcf -x ID,QUAL,INFO,^FMT/GT,^FMT/BAF,^FMT/LRR $pfx.vcf && \
/bcftools  index -f $pfx.unphased.bcf

n=$(/bcftools  query -l $pfx.unphased.bcf|wc -l); \
ns=$((n*98/100)); \
echo '##INFO=<ID=JK,Number=1,Type=Float,Description="Jukes Cantor">' | \
  /bcftools  annotate --no-version -Ou -a $dup -c CHROM,FROM,TO,JK -h /dev/stdin $pfx.unphased.bcf | \
 /bcftools  +/fill-tags.so --no-version -Ou -- -t NS,ExcHet | \
  bcftools  +mochatools.so --no-version -Ou -- -x $sex -G | \
  bcftools  annotate --no-version -Ob -o $pfx.xcl.bcf \
    -i 'FILTER!="." && FILTER!="PASS" || JK<.02 || NS<'$ns' || ExcHet<1e-6 || AC_Sex_Test>6' \
    -x FILTER,^INFO/JK,^INFO/NS,^INFO/ExcHet,^INFO/AC_Sex_Test && \
 bcftools  index -f $pfx.xcl.bcf

Then, when I ran eagle:

for chr in {1..22} X; do
  eagle \
    --geneticMapFile $map \
    --chrom $chr \
    --outPrefix $pfx.chr$chr \
    --numThreads 4 \
    --vcfRef $kgp_pfx${chr}$kgp_sfx.bcf \
    --vcfTarget $pfx.unphased.bcf \
    --vcfOutFormat b \
    --noImpMissing  \
    --outputUnphased \
    --vcfExclude $dir/$pfx.xcl.bcf && bcftools index -f $pfx.chr$chr.bcf
done

I get the following: ERROR: Could not open X.xcl.bcf for reading: unknown file type.

I have full permissions on the file. I am not sure if it's the eagle problem or it's the file generating issues.

Can you please help me with this?

Thank you.

**Comment by freeseek** [comment]
It seems like you created the $pfx.xcl.bcf but you are trying to access the $dir/$pfx.xcl.bcf file instead. It should be consistent.

**Comment by aleshchyk** [comment]
I fixed $dir/$pfx.xcl.bcf to $pfx.xcl.bcf in the script and it did not work.

**Comment by freeseek** [comment]
I did not write eagle so I can only speculate like anybody else as to why it is giving you that error. Check the X.xcl.bcf file to see what is wrong with it.

**Comment by aleshchyk** [comment]
Thanks for your help. I will close this.
