### ISSUE TITLE
Include other metrics in the vcf output

### ISSUE THREAD

**Issue by raonyguimaraes** [freeseek/gtc2vcf#16]
Hi there,

I'm looking for a way to include the "cluster separation" [0-1] metric to the output vcf produced using the gtc2vcf method. Could someone please tell me if this would be possible and how I could change the code to achieve this goal? 

Thank you!

**Comment by freeseek** [comment]
Yes, I will include in the VCF file additional metrics from the EGT file if that is useful to you. I will get back to you soon.

**Comment by raonyguimaraes** [comment]
Thank you Giulio!

**Comment by freeseek** [comment]
The latest version now includes the following INFO fields in the VCF when an EGT file is included:
```
GenTrain_Score
Orig_Score
Edited
Cluster_Sep
Intensity_Threshold
```

**Comment by raonyguimaraes** [comment]
Thank you!
