### ISSUE TITLE
idat to vcf without bpm file

### ISSUE THREAD

**Issue by KarthickRajaNarayanan** [freeseek/gtc2vcf#17]
Hi  @freeseek  ,

I dont have the bpm manifest file but I have csv manifest file. Is there any options to convert the idat file to gtc & vcf?

Regards,
Karthick

**Comment by freeseek** [comment]
You don't need the BPM to convert GTC files to VCF files (unless you want to include the normalized intensities in the VCF) but you will need the BPM to convert IDAT files to GTC files as this is needed by the Illumina GenCall utility. What BPM file do you need?

**Comment by KarthickRajaNarayanan** [comment]
Thanks for your quick respose!

Yes. I need the bpm file for idat to gtc file conversion. I have csv file. Is there any way to convert the bpm to csv?

Thanks,
Karthick

**Comment by freeseek** [comment]
You cannot convert the CSV to the original BPM. There is some information about normalization that cannot be retrieved. You could in theory convert the CSV to your own BPM file once you specify a normalization BeadSetID order. But gtc2vcf does not have a BPM writer. What is the name of the CSV file you have?

**Comment by KarthickRajaNarayanan** [comment]
Hi Giulio,

This is the name of my .csv file.

"GSAMD-24v1-0_20011747_A1.csv"

Regards,
Karthick

**Comment by freeseek** [comment]
https://www.dropbox.com/sh/d6kn6o9ahxq9k4c/AACLsOlh2SOgpKX-bl71Gf1Ha?dl=0

**Comment by KarthickRajaNarayanan** [comment]
Thanks a lot Giulio!

Best,
Karthick

**Comment by hyunnnie** [comment]
Hello @freeseek! 

I also don't have a bpm file. Could you please help?
I have only idat, sample csv file. Is there anything I can do? 

I am so sorry for interrupt!

Thank you, 
Seohyun

**Comment by freeseek** [comment]
What happens if you run the following?
```
bcftools +gtc2vcf -i ######.idat
```
The output might give you a guess as to what array the IDAT was generated from. Feel free to post the output here

**Comment by KarthickRajaNarayanan** [comment]
> Hello @freeseek!
> 
> I also don't have a bpm file. Could you please help? I have only idat, sample csv file. Is there anything I can do?
> 
> I am so sorry for interrupt!
> 
> Thank you, Seohyun

You need to check with the vendor of the kit that you used for sequencing. They should have the bpm file.

**Comment by KarthickRajaNarayanan** [comment]
> What happens if you run the following?
> 
> ```
> bcftools +gtc2vcf -i ######.idat
> ```
> 
> The output might give you a guess as to what array the IDAT was generated from. Feel free to post the output here

I don't have the output file now since it was 2 years back. But it was giving me the VCF file for the samples when i feed the gtc files of samples, initial idat files and the reference genome.

**Comment by Antidington** [comment]
Hi @freeseek ,

I am writing to inquire this BPM file `GSAMD-24v2-0_20024620_A1.bpm`. I didn't find any information on the Illumina support center. I would be appreciate if you can give more information on this issue!

Thanks,
Jichen

**Comment by freeseek** [comment]
The `GSAMD-24v2-0_20024620` is a custom Illumina array, so cluster and manifest files are not freely available for download. You can reach out to me by email if you need more information

**Comment by Antidington** [comment]
> The `GSAMD-24v2-0_20024620` is a custom Illumina array, so cluster and manifest files are not freely available for download. You can reach out to me by email if you need more information

Thank you so much! I have used this email - wenjichen.big@gmail.com to contact you.

**Comment by Antidington** [comment]
> The `GSAMD-24v2-0_20024620` is a custom Illumina array, so cluster and manifest files are not freely available for download. You can reach out to me by email if you need more information

Thank you so much! I have used this email - wenjichen.big@gmail.com to contact you.

**Comment by zhou-ran** [comment]
> The `GSAMD-24v2-0_20024620` is a custom Illumina array, so cluster and manifest files are not freely available for download. You can reach out to me by email if you need more information

@freeseek 
Hi Giulio, 

Could you send me a copy of `GSAMD-24v2-0_20024620.bpm` file, thank you very much.

Here is my email, ranzhou1005@gmail.com

Ran

**Comment by yxlong-science** [comment]
Hi @freeseek ,

When converting IDAT to VCF, I was also limited by the BPM manifest file and EGT cluster file (GSAMD-24v2-0_20024620). I contacted you via email and am looking forward to your reply.

Thanks,
Yuexuan

**Comment by freeseek** [comment]
See [here](https://www.dropbox.com/scl/fo/47401huc1grnlqly5kg2u/h?rlkey=6kjjkohjgsq4wow8nr26ypcqm&dl=0) but also notice that it is possible to use Illumina's GSA-24v2-0 public manifest and cluster files to process the GSAMD-24v2-0_20024620 IDATs, although you will lose all the probes associated with the custom version of the array

**Comment by yxlong-science** [comment]
Thank you for your reply!

**Comment by franciscodavid** [comment]
I'm sorry to comment on this old and closed issue, but is it still possible that any of you could share the bpm/egt files for `GSAMD-24v2-0_20024620` ?

I have some old IDATs that I need to convert to vcf. That's the array reported with `bcftools +gtc2vcf`, and I wanted to avoid the generic manifest.

Thanks in advance.

--
Fran

**Comment by freeseek** [comment]
The bpm and csv manifest files for the `GSAMD-24v2-0_20024620` array are available at the following ftp URL:
```
ftp://webdata:webdata@ftp.illumina.com/Public_Docs/Genotyping_Array_Support_Files/Archives/Consortium%20Global%20Screening%20Array/Consortium%20GSA%20v2%20+MD/GSAMD-24v2.0%20(Build%2037)
```
However, you will not find the egt cluster file there. My understanding is that you will have to create that separately using GenomeStudio. Currently BCFtools/idat2gtc will normalize and genotype array intensity data like Illumina Gencall does but it does not do the clustering
