### ISSUE TITLE
Could not initialize gtc2vcf.so, neither run or init found

### ISSUE THREAD

**Issue by oneilep** [freeseek/gtc2vcf#2]
Hello, I am trying to use the "Convert Illumina GTC files to VCF" example shown in the README, but I am getting this error:

Writing to .
**Could not initialize gtc2vcf.so, neither run or init found**
[E::bcf_hdr_read] Input is not detected as bcf or vcf format
Failed to open -: unknown file type
Failed to open -: unknown file type

Looking in the file, there is a `run` function defined, but no `init` function, and bcftools vcfplugin.c appears to be checking for both.

I am using bcftools version 1.9. Any idea what could be causing this?

**Comment by freeseek** [comment]
You don't need both init() and run() for a working bcftools plugin. Can you try to see whether the run() function is indeed in the shared object file?
```
objdump -T gtc2vcf.so | grep run
```
Also, try to run bcftools plugin with the `-v` verbose option. It might give you further insights into your issue.

**Comment by oneilep** [comment]
I don't see a run function in the output

$ objdump -T plugins/gtc2vcf.so 

plugins/gtc2vcf.so:     file format elf64-x86-64

DYNAMIC SYMBOL TABLE:
0000000000000560 l    d  .init	0000000000000000              .init
0000000000000000  w   D  *UND*	0000000000000000              __gmon_start__
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 exit
0000000000000864 g    DF .fini	0000000000000000  Base        _fini
00000000000007f0 g    DF .text	0000000000000030  Base        hts_bcf_wmode
0000000000000000  w   D  *UND*	0000000000000000              _ITM_deregisterTMCloneTable
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 vfprintf
0000000000000000  w   D  *UND*	0000000000000000              _ITM_registerTMCloneTable
0000000000000000  w   DF *UND*	0000000000000000  GLIBC_2.2.5 __cxa_finalize
0000000000000720 g    DF .text	0000000000000018  Base        version
0000000000000740 g    DF .text	00000000000000a3  Base        error
0000000000200b30 g    D  *ABS*	0000000000000000  Base        __bss_start
0000000000200b40 g    D  *ABS*	0000000000000000  Base        _end
0000000000000000      DO *UND*	0000000000000000  GLIBC_2.2.5 stderr
0000000000200b30 g    D  *ABS*	0000000000000000  Base        _edata
0000000000000000      D  *UND*	0000000000000000              hts_version
0000000000000560 g    DF .init	0000000000000000  Base        _init

And -v didn't give any additional information.

**Comment by oneilep** [comment]
I was able to fix this. For some reason I had a completely empty gtc2vcf.c file and a gtc2vcf.c.1 file with the actual code (I guess the initial download failed?). After deleting the empty file and renaming the .1 copy it compiled correctly with the run function and everything.
