### ISSUE TITLE
 will generate same output as using AutoConvert via Beeline?

### ISSUE THREAD

**Issue by wangfan860** [freeseek/gtc2vcf#21]
Hello,

Thank you for the handy tool! I'm able to generate gtc files from idat files using your software. However, I'd like to know if the results are the same as Beeline's AutoConvert function. I don't have a windows os with illumina, so I can't compare by myself. I really appreciate if anyone has any inputs.

Thanks
Fan

**Comment by freeseek** [comment]
I have no way to run AutoConvert.exe on Windows, but I can tell you that for one array I had compared at one point the results of AutoConvert.exe and iaap-cli, both run on Linux, and they seemed identical to me (with the exception of the autocall_date and autocall_version fields). When you run AutoConvert.exe on Linux there is a function (findClosestSitesToPointsAlongAxis) that needed to be rewritten. Other than that, the same code is run, both on Linux and Windows. Are you worried that this specific function behaves differently from its Windows counterpart?
