### ISSUE TITLE
No releases

### ISSUE THREAD

**Issue by pneerincx** [freeseek/gtc2vcf#25]
Commit messages contain phrases like new release or new version, but there are no versioned releases/tags for this repo. That makes it hard to create a reproducible deployment for reproducible science...

**Comment by freeseek** [comment]
@pneerincx yes, it is a bit complicated to make releases due to the strong dependency on HTSlib and BCFtools. I have not decided how to settle that yet. For now you could either use the combination of BCFtools and the latest commit (e.g. 1.10.2-0c4cd07) or you can use the releases from this [page](http://software.broadinstitute.org/software/gtc2vcf).

**Comment by pneerincx** [comment]
@freeseek I understand the dependency on BCFtools and HTSlib complicates the installation, but that should not stop you from hitting the `draft new release` button. All you have to do is settle on a version number and you are done. This will give us at least a version for gtc2vcf. If that version mentions in a README, release notes or something similar which version of HTSlib and BCFtools it was tested with that would be a nice bonus, but even without reference to a specific version of those dependencies a versioned release for the gtc2vcf code is welcome!

**Comment by freeseek** [comment]
As I said, for now, there are releases on this page: http://software.broadinstitute.org/software/gtc2vcf

**Comment by pneerincx** [comment]
> As I said, for now, there are releases on this page: http://software.broadinstitute.org/software/gtc2vcf

Is that website maybe only accessible from some internal network at the Broad?
* http://software.broadinstitute.org is resolvable, but returns a rather empty page containing only the DNS name: software.broadinstitute.org
* http://software.broadinstitute.org/software as well as http://software.broadinstitute.org/software/gtc2vcf return:
   ```
   Not Found
   The requested URL ... was not found on this server.
   ```

**Comment by pneerincx** [comment]
Looks like error is caused by an automatic redirect from http to https. The https version of the URL returns the "Not Found" error. Could be a browser issue. Anyway, the http URL works and I see the BCFtools + HTSlib version is listed there for each gtc2vcf version: thanks!
