### ISSUE TITLE
build in macOS

### ISSUE THREAD

**Issue by smajidian** [freeseek/gtc2vcf#32]
Dear gtc2vcf team

I was wondering whether a prebuilt binary file for mac exists? 
if not,  is there any recipe/instruction to build the package from source in macos?

Thank you in advance.

Regards,
Sina

**Comment by freeseek** [comment]
No binaries for mac are provided but you can follow the [installation](https://github.com/freeseek/gtc2vcf#installation) instructions and it should compile on a mac.
