### ISSUE TITLE
Question affy2vcf

### ISSUE THREAD

**Issue by bolton-lab** [freeseek/gtc2vcf#33]
Hi Giulio,

Quick question, I see affy2vcf can convert cel to chp and chp to vcf.  I am just wondering if this is required to do two steps to get from cel to vcf?  I don't see in description requiring this and I know PennCNV goes from cel to vcf but requires multiple steps.  Let me know whether we can go straight from CEL to VCF.  Thanks.
Brian

**Comment by bolton-lab** [comment]
Sorry, I'll add what I tried.  This code just indicated `Reading AGCC file /Users/brian/Downloads/GW_SNP5_AGCC_CEL_1/NA07022_Op1_011206_VnV_A04_r1.CEL`

```
bcftools +affy2vcf \
  --no-version -Ou \
  --fasta-ref $ref \
  --calls /Users/brian/output/brlmm-p.calls.txt \
  --confidences /Users/brian/output/brlmm-p.confidences.txt \
  --cel /Users/brian/Downloads/GW_SNP5_AGCC_CEL_1/*.CEL
```

**Comment by freeseek** [comment]
+affy2vcf can read the content of CEL and CHP files and can convert CHP files to VCFs (provided a `.snp-posteriors.txt` file is also provided). The ability to read CEL files is merely to understand what array was used to generate them and when the array was scanned. The error `does not contain multi data type analysis as` most likely means that you are trying to read a CEL file as if it was a CHP file. You will still need to call genotypes using the APT suite. I do warn you though that for non-Axiom arrays, only the SNP 6.0 array is currently supported, as APT does not compute bi-dimensional cluster centers for previous arrays, and for Axiom arrays I don't know how you can generate CHP files using the APT suite. For Axiom arrays currently the only option I know is to create `.calls.txt/.summary.txt/.snp-posteriors.txt` table files from CEL files and input these into +affy2vcf. I will add a section to make this more clear but for now check [here](https://github.com/freeseek/gtc2vcf#convert-affymetrix-chp-files-to-vcf) and replace `--chps` with `--calls`, `--confidences`, and `--summary` (CHP files are binary files that contain the same data as the latter three tables). Also check the examples provided when running `bcftools +affy2vcf` without any option.
