### ISSUE TITLE
affy2vcf: How to make the IDs of generated vcf files be rsid from annotation files given by Affymetrix but not probeset id?

### ISSUE THREAD

**Issue by YuquanW** [freeseek/gtc2vcf#38]
Hi,

I had succeeded transforming CEL files to vcf files, but I found the ID column of vcf files were still probeset ID. I have tried 

```
bcftools annotate -a 00-All.vcf.gz -c ID xxx.vcf.gz
```

to make the ID column annotated by rsids, but there are still some SNPs failing to be annotated for 00-All.vcf.gz not containing all the SNPs from GenomeWideSNP_6.na35.annot.csv. Is there anyway to annotate the IDs in the step

```
bcftools +affy2vcf \
  --no-version -Ou \
  --csv $csv_manifest_file \
  --fasta-ref $ref \
  --chps $path_to_chp_folder \
  --snp $path_to_txt_folder/AxiomGT1.snp-posteriors.txt \
  --extra $out_prefix.tsv | \
  bcftools sort -Ou -T ./bcftools-sort.XXXXXX | \
  bcftools norm --no-version -Ob -o $out_prefix.bcf -c x -f $ref && \
  bcftools index -f $out_prefix.bcf
``` 

or transform the  GenomeWideSNP_6.na35.annot.csv to vcf annotation file? Thank you!

**Comment by freeseek** [comment]
Affymetrix manifest files have three annotations:
```
PROBE_SET_ID
DBSNP_RS_ID
AFFY_SNP_ID
```
The `+gtc2vcf` plugin uses `PROBE_SET_ID` in the VCF ID field and `DBSNP_RS_ID` and `AFFY_SNP_ID` in the INFO fields. However, this behavior can be modified downstream with a simple command.

The following command will put the `PROBE_SET_ID` back into the INFO field and move the `DBSNP_RS_ID` in the ID field:
```
bcftools annotate \
  --no-version -Ou \
  --annotations xxx.vcf.gz \
  --columns PROBE_SET_ID:=ID \
  --set-id %DBSNP_RS_ID \
  xxx.vcf.gz | \
bcftools annotate \
  --no-version -Oz \
  --output yyy.vcf.gz \
  --remove INFO/DBSNP_RS_ID
```

Do notice though that `DBSNP_RS_ID` and `AFFY_SNP_ID` are not unique identifiers as different `PROBE_SET_ID` values can correspond to the same `DBSNP_RS_ID` or `AFFY_SNP_ID`. This is okay for a VCF, but it could be problematic if you convert to plink format and use the VCF ID column for the variant IDs.

Notice also that you cannot use the above command on a VCF stream as the `--annotations/--columns` combo needs an indexed VCF.

**Comment by YuquanW** [comment]
Thanks a lot for your time and your kind advice!
