### ISSUE TITLE
how to convert CEL to CHP?

### ISSUE THREAD

**Issue by lizhan96** [freeseek/gtc2vcf#43]
After I install bcftools, I follow the README document and run the following code, but there is a error message.
`path_to_output_folder="..."
cel_list_file="..."
apt-probeset-genotype \
  --analysis-files-path . \
  --xml-file GenomeWideSNP_6.apt-probeset-genotype.AxiomGT1.xml \
  --out-dir $path_to_output_folder \
  --cel-files $cel_list_file \
  --special-snps GenomeWideSNP_6.specialSNPs \
  --chip-type GenomeWideEx_6 \
  --chip-type GenomeWideSNP_6 \
  --table-output false \
  --cc-chp-output \
  --write-models \
  --read-models-brlmmp GenomeWideSNP_6.generic_prior.txt`

The question is that what software should be install when use [apt-probeset-genotype]?

**Comment by lizhan96** [comment]
> FATAL ERROR:Can't read header for GenomeWideSNP_6.cdf. Description: Unable to open the file.
i get this error message.

**Comment by freeseek** [comment]
If the error is: `FATAL ERROR:Can't read header for GenomeWideSNP_6.cdf. Description: Unable to open the file.`

Then you need the file `GenomeWideSNP_6.cdf` in the analysis files path. You can follow the instruction [here](https://github.com/freeseek/gtc2vcf#convert-affymetrix-cel-files-to-chp-files) to obtain that file
