### ISSUE TITLE
ERROR in converting CHP to VCF

### ISSUE THREAD

**Issue by lizhan96** [freeseek/gtc2vcf#44]
hi, devoloper. After I install bcftools-1.11 and gtc2vcf, I run the following code
`/data_6t/lizhan/02.software/bcftools-1.11/bcftools +affy2vcf \
	  --no-version -Ou \
	    --csv $csv_manifest_file \
	      --fasta-ref $ref \
	        --chps $path_to_chp_folder \
		  --snp $path_to_txt_folder/AxiomGT1.snp-posteriors.txt \
		    --extra $out_prefix.tsv`

but there are some error message.

> Writing to ./bcftools-sort.ribgu4
/data_6t/lizhan/02.software/bcftools-1.11/plugins/affy2vcf.so:
	dlopen   .. /data_6t/lizhan/02.software/bcftools-1.11/plugins/affy2vcf.so: undefined symbol: set_wmode
affy2vcf:
	dlopen   .. affy2vcf: cannot open shared object file: No such file or directory

The bcftools plugin "affy2vcf" was not found or is not functional in
	BCFTOOLS_PLUGINS="/data_6t/lizhan/02.software/bcftools-1.11/plugins".

- Is the plugin path correct?

- Run "bcftools plugin -l" or "bcftools plugin -lvv" for a list of available plugins.

Could not load "affy2vcf".

**Comment by freeseek** [comment]
The current code for the affy2vcf plugin requires BCFtools version 1.14 or newer.
