### ISSUE TITLE
gtc2vcf cannot open gtc files 

### ISSUE THREAD

**Issue by mahaaamir** [freeseek/gtc2vcf#45]
I used the GenCall algorithm to generate gtc files. My generated gtc files are not in a readable format- is this supposed to be the case? (I have set the LANG variable as instructed). My egt and bpm files are also correctly called on, and GenCall seems to run fine. 
However, the gtc2vcf plugin is also unable to read in these gtc files.

This is the command I have used to generate gtc files:
LANG="en_US.UTF-8" $HOME/bin/iaap-cli/iaap-cli gencall /path/to/manifest/file.bpm /path/to/cluster/file.egt /path/to/output/folder --idat-folder /path/to/idat/folder/--output-gtc --gender-estimate-call-rate-threshold -0.1

Am I generating gtc files incorrectly?

**Comment by freeseek** [comment]
The GTC files are binary files so they are not in a readable format (see [here](https://github.com/Illumina/BeadArrayFiles/blob/develop/docs/GTC_File_Format_v5.pdf) for the file specification). If you want to explore the content of a GTC file, you can use the following command:
```
bcftools +gtc2vcf --verbose input.gtc
```
What output do you get if you try the command?

**Comment by mahaaamir** [comment]
Below is a portion of the output I got; 

gtc2vcf 2022-01-12 https://github.com/freeseek/gtc2vcf
Reading GTC file 800.gtc
Illumina, Inc.
[Heading]
Descriptor File Name,800.gtc
GTC genotype file version,5
Number of TOC entries,31
Number of SNPs,1733222
Ploidy,1
Ploidy Type,0
Sample name,
Sample plate,
Sample well,
Cluster file,Multi-EthnicGlobal_D1_ClusterFile.egt
SNP manifest,Multi-EthnicGlobal_D2.bpm
Imaging date,12/2/2021 2:54:09 AM
AutoCall date,04/28/2022 1:25 PM
AutoCall version,3.0.0
Number of normalization transforms,63
Number of controls X,92
Number of controls Y,92
Name of the scanner,N0733
Pmt Green,0
Pmt Red,0
Version of the scanner software used,4.0.0.147
Name of the scanner user,iscan
Call Rate,0.958901
Computed Gender,M
LogR deviation,0.131587
GenCall score - 10th percentile,0.429314
DX,0
GenCall score - 50th percentile,0.827488
Number of valid calls,1676399
Number of invalid calls,71851
Number of loci that are "Intensity Only" or "Zeroed",0
P05 X,663
P50 X,2816
P95 X,16956
P05 Y,341
P50 Y,3807
P95 Y,7543
Sentrix identifier for the slide,800
[Assay]
Raw X,Raw Y,GType,Top Alleles,Score,B Allele Freq,Log R Ratio
902,5189,BB,CC,0.466913,1.000000,0.129283
710,5165,BB,GG,0.492016,1.000000,0.034661
