### ISSUE TITLE
idat or gtc in command line

### ISSUE THREAD

**Issue by jeantristanb** [freeseek/gtc2vcf#46]
I will want to used idat file more than gtc, do you have an example of command line? 
`bcftools +gtc2vcf   -Ou   --bpm .bpm    --egt  egt    --idat filelink    --fasta-ref  fasta   --extra gtc2vcf_idat".tsv"  --output gtc2vcf_idat".vcf.gz" --threads 35 --output-type z`
with filelink contains each idat file 
error that I obtained ; 
`The --idat option can only be used alone or with option --gtcs`
Could you explained more how to use idat with gtc2vcf? what algoritms ? what is the interrest?
thank you

**Comment by freeseek** [comment]
hi @jeantristanb, the gtc2vcf plugin can peek into the IDATs and can convert GTCs to VCF. However, you cannot convert IDATs to VCF with the plugin, as the IDATs do not contain genotypes which are generated by the Illumina GenCall algorithm. The main reason gtc2vcf allows you to peak inside the IDATs is to help you guess which array the IDATs were generated with. This might guide in understanding which manifest files to use when converting IDATs to GTCs and when converting GTCs to VCF.
