### ISSUE TITLE
Can't install wine32 on my machine

### ISSUE THREAD

**Issue by Celestic1** [freeseek/gtc2vcf#5]
I have wine64 installed, but the commands I ran from read me also needed wine32. So I switched to a 32 bit vm and then it needs wine64. Pretty frustrated with installing this pipeline as I would prefer using this than running beeline 100x to get my idat to gtc.

**Comment by freeseek** [comment]
You cannot use wine32 as it will not install AutoConvert. You have to use wine64. Another solution, possibly easier but less elegant, is to install AutoConvert and GenomeStudio using a Windows machine and then copy the required files in your Linux installation.
