### ISSUE TITLE
plink matrix format

### ISSUE THREAD

**Issue by gevro** [freeseek/gtc2vcf#51]
Hi, I have data from dbGaP that is in 'plink matrix format'. Can I use this tool? If not, what is the best way to prepare this data for MoCHa?

**Comment by freeseek** [comment]
Plink format does not include probe intensity data so it inherently misses the data needed to run an mCA (or CNV) caller. Usually dbGAP should give you access to IDATs for Illumina data and to CELs for Affymetrix data though

**Comment by gevro** [comment]
dbGaP doesn't have IDAT files for this study. I have 'ind' files that have this header:
```
#Study
#Platform- Illumina 550K.
#SubjectID(Study Participant de-identifier ID)- GWAS-003-997483
#SampleID (Specimen de-identified ID)- GWAS-S003-76405.
#local_SnpID,Allele_1,Allele_2,Quality Score,QC Status,Normalized X Intensity,Normalized Y Intensity,Raw X Intensity,Raw Y Intensity
```

Is this possible to use with your conversion tool?

**Comment by freeseek** [comment]
Unlikely. I don't know what format that is. There is a `--genome-studio` option that will convert some GenomeStudio file in matrix format but it will not convert everything out there, as GenomeStudio tables are not a format (i.e., there is no specification).

**Comment by freeseek** [comment]
A GenomeStudio file that can be imported by +gtc2vcf should look like this (ideally with multiple samples on each row):
```
Chromosome      Position        IlmnStrand      SNP     Name    SM.GType        SM.Score        SM.Theta        SM.R    SM.B Allele Freq        SM.Log R Ratio
9       139906359       BOT     [T/C]   200003  AA      0.9299  0.029   1.300   0.0027  0.2150
9       139926402       TOP     [A/G]   200006  AB      0.7877  0.435   2.675   0.4742  0.3024
2       220084902       BOT     [T/C]   200047  AA      0.8612  0.083   0.476   0.0532  -0.1173
2       220089685       TOP     [C/G]   200050  BB      0.8331  0.995   1.499   1.0000  0.3068
```

Alternatively, +mocha will accept VCFs formatted as explained in the [documentation](https://github.com/freeseek/mocha/#data-preparation)

Do understand that +gtc2vcf and +mocha are designed to work with standardized file formats exactly to obviate these types of issues and there is no official support for non-standardized file formats

**Comment by gevro** [comment]
Thanks. Doesn't look feasible to me. I'll keep trying to track down the original CEL and IDAT files.
