### ISSUE TITLE
Error for installing AutoConvert

### ISSUE THREAD

**Issue by hyunnnie** [freeseek/gtc2vcf#52]
Hello, @freeseek 

Currently, I am fail to download the autoconvert software. 
I am using Ubuntu server 22.04. And I got error like below. 

`(msiextract:3959): WARNING **: 11:44:49.173: open file failed for AutoConvertInstaller.msi`

Any help would be greatly appreciated. 

kind regards, 
hyunnnie

**Comment by freeseek** [comment]
Were you even able to get the `AutoConvertInstaller.msi` file? You probably were not able to download autoconvert-software-v2-0-1-installer.zip and were unable to uncompress it as a result. You can login into the Illumina website to download `autoconvert-software-v2-0-1-installer.zip` manually. Alternatively, if you are unable to download it, as explained in the instructions, reach out to me via email
