### ISSUE TITLE
Input not detected as vcf or bcf format

### ISSUE THREAD

**Issue by cantlap** [freeseek/gtc2vcf#56]
Getting this error:

[E::bcf_hdr_read] Input is not detected as bcf or vcf format
bcftools: bgzf.c:982: bgzf_read: Assertion `fp->is_write == 0' failed.
Failed to open -: unknown file type
index: "-" is in a format that cannot be usefully indexed

When I try to run this script file:

bpm_manifest_file="/home/cantlap/illumina_gtc_conversion/gsa2022_redo/GSA_Product_Files/GSA-24v3-0_A2.bpm"
csv_manifest_file="/home/cantlap/illumina_gtc_conversion/gsa2022_redo/GSA_Product_Files/GSA-24v3-0_A2.csv"
egt_cluster_file="/home/cantlap/illumina_gtc_conversion/gsa2022_redo/GSA_Product_Files/GSA-24v3-0_A1_ClusterFile.egt"
path_to_gtc_folder="/home/cantlap/illumina_gtc_conversion/gsa2022_redo/gtcList_gsa2022_redo.txt"
ref="/home/cantlap/illumina_gtc_conversion/gsa2022_redo/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"
out_prefix="/home/cantlap/illumina_gtc_conversion/gsa2022_redo/outputVCF_files"
bcftools +gtc2vcf \
  --no-version -Ou \
  --bpm $bpm_manifest_file \
  --csv $csv_manifest_file \
  --egt $egt_cluster_file \
  --gtc-list $path_to_gtc_folder \
  --fasta-ref $ref \
  --output $out_prefix.tsv | \
  bcftools sort -Ou -T ./bcftools. | \
  bcftools norm --no-version -Ob -c x -f $ref | \
  tee $out_prefix.bcf | \
  bcftools index --force --output $out_prefix.bcf.csi

**Comment by freeseek** [comment]
When you use `--output` the `bcftools +gtc2vcf` plugin will not pipe anything to stdout for the `bcftools sort` command to read

**Comment by cantlap** [comment]
When I run with the --extra tag which is what is listed on the instructions it gives this error though:

bash runGTC2VCF.sh 
Writing to ./bcftools.
gtc2vcf: unrecognized option '--extra'

About: convert Illumina GTC files containing intensity data into VCF (2018-09-07)

Usage: bcftools +gtc2vcf [options] <A.gtc> [...]

**Comment by freeseek** [comment]
You are using an extremely old versin of `bcftools +gtc2vcf` that does not have that option
