### ISSUE TITLE
## can't find file to patch at input line 3

### ISSUE THREAD

**Issue by cbiOPela** [freeseek/gtc2vcf#6]
Hi!
When using your fantastic tool towards the readme file, i get this step and i do not know how to proceed. In fact, I jump to the next step (compile htslib and bcftools...). At the end I can use the converter IDAT to GTC for llumina but I want to run the whole tool.
Coul you please help me with this?

I paste the error and some aditional information

# Add patch (to allow the fixref plugin to flip BAF values) and code for plugins

/bin/rm -f bcftools/plugins/{gtc2vcf.c,affy2vcf.c,fixref.patch}
wget -P bcftools/plugins https://raw.githubusercontent.com/freeseek/gtc2vcf/master/{gtc2vcf.c,affy2vcf.c,fixref.patch}
cd bcftools/plugins && patch < fixref.patch && cd ../..

the error is:
can't find file to patch at input line 3
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|--- fixref.c    2018-09-05 12:00:00.000000000 -0500
|+++ fixref.c    2018-09-05 12:00:00.000000000 -0500
--------------------------
File to patch:

**Comment by freeseek** [comment]
You need to make sure you downloaded the fixref.patch file in the bcftools/plugins/ directory and then run the patch command from there. This could be simplified in the future by convincing the author of bcftools to include something like what the patch does in the bcftools +fixref main code base.
