### ISSUE TITLE
Error while running linsolve1

### ISSUE THREAD

**Issue by Dazcam** [freeseek/gtc2vcf#66]
Hi there,

I'm trying to run the `bcftools +idat2gtc` plugin on some files from the Yazar 2022 dataset. 

I've unzipped a couple of the idat files to test (and have tested numerous pairs):

<img width="265" alt="Screenshot 2024-06-20 at 14 24 49" src="https://github.com/freeseek/gtc2vcf/assets/22788904/8f2c50c2-f9e2-410c-b4a0-8d57629630d0">

When running the following:

```bash
bcftools +idat2gtc \
--bpm ../resources/downloads/GSA-24v3-0_A1.bpm \
--egt ../resources/downloads/GSA-24v3-0_A1_ClusterFile.egt \
--idats ../resources/downloads/test/ \
--output ../resources/downloads/gtc_files
```

The the process starts, but throws the following error during normalisation:

<img width="594" alt="Screenshot 2024-06-20 at 14 28 51" src="https://github.com/freeseek/gtc2vcf/assets/22788904/cbec6066-94c0-479a-b354-db2b5207c20c">

I'm running this in a singularity container I built following the install commands specified on your README page.

<details>
  <summary>Definition file</summary>
  
```
Bootstrap: docker 
From: ubuntu:22.04 

%environment
	TZ=UTC
	DEBIAN_FRONTEND=noninteractive

%post 
        export TZ=UTC
        export DEBIAN_FRONTEND=noninteractive
	apt-get update -y 
	apt-get install -y libbz2-dev libssl-dev liblzma-dev libgsl0-dev make bzip2 libcurl4-openssl-dev
	apt-get install -y wget unzip git g++ zlib1g-dev bwa unzip samtools 
	
	wget -P tmp/ https://github.com/samtools/bcftools/releases/download/1.20/bcftools-1.20.tar.bz2 
	tar xjvf tmp/bcftools-1.20.tar.bz2 -C tmp
	
	/bin/rm -f tmp/bcftools-1.20/plugins/idat2gtc.c 
	/bin/rm -f tmp/bcftools-1.20/plugins/gtc2vcf.c 
	/bin/rm -f tmp/bcftools-1.20/plugins/gtc2vcf.h 
	/bin/rm -f tmp/bcftools-1.20/plugins/affy2vcf.c 

	wget -P tmp/bcftools-1.20/plugins https://raw.githubusercontent.com/freeseek/gtc2vcf/master/idat2gtc.c 
	wget -P tmp/bcftools-1.20/plugins https://raw.githubusercontent.com/freeseek/gtc2vcf/master/gtc2vcf.c 
	wget -P tmp/bcftools-1.20/plugins https://raw.githubusercontent.com/freeseek/gtc2vcf/master/gtc2vcf.h 
	wget -P tmp/bcftools-1.20/plugins https://raw.githubusercontent.com/freeseek/gtc2vcf/master/affy2vcf.c 
	 
	make -C tmp/bcftools-1.20/ 

	/bin/cp tmp/bcftools-1.20/bcftools bin/ 
	/bin/cp tmp/bcftools-1.20/plugins/idat2gtc.so bin/ 
	/bin/cp tmp/bcftools-1.20/plugins/gtc2vcf.so bin/ 
	/bin/cp tmp/bcftools-1.20/plugins/affy2vcf.so bin/

        echo 'export PATH="/bin/:$PATH"' >> $SINGULARITY_ENVIRONMENT
        echo 'export BCFTOOLS_PLUGINS="/bin/"' >> $SINGULARITY_ENVIRONMENT
```
</details>

Running `bcftools +gtc2vcf -i ../resources/downloads/test//GSM5902662_203182650277_R07C01_Grn.idat` appears to work as expected:

<details>
  <summary>gtc2vcf log</summary>
  
<img width="1406" alt="Screenshot 2024-06-20 at 14 58 07" src="https://github.com/freeseek/gtc2vcf/assets/22788904/2268234c-e09f-4ad8-83e4-a2f8567f4d77">

</details>

I'm a bit stumped as how to resolve this.

Any suggestions would be greatly appreciated.

**Comment by freeseek** [comment]
@Dazcam thank you for your feedback and for reaching out. This is a problem related to the normalization algorithm. Is this an isolated issue for you, i.e., does the tool work fine with other IDAT pairs for the same array? Did you check whether the same issue arises with running the Illumina tool? Indeed sometimes the Illumina tool does also fail during normalization. I would be happy to run some tests myself if you can find a way to let me have a copy of those two IDAT files

**Comment by Dazcam** [comment]
@freeseek Thanks for responding so swiftly.

Unfortunately, I'm working on a Mac so I'm unable to test this on the Illumina tools as they only support Windows based platforms. Your package seemed like the ideal (in fact the only!) solution.
I have tested a few idat pairs using `idat2gtc` and they all failed with the same error.

In terms of accessing the idats for testing you can either access the entire collection using wget from the GEO repo:

```bash
wget https://ftp.ncbi.nlm.nih.gov/geo/series/GSE196nnn/GSE196830/suppl/GSE196830_RAW.tar
```

Or if you send me an email address I can send some of the ideates through via our institutions FastFile service.

Incidentally, I also got the same error when running this in the [Illiad container](https://github.com/ncherric/Iliad). (To which I added the `idat2gtc plugin` to it as it was the only one missing.)

Many thanks for looking into this for me.

**Comment by freeseek** [comment]
Even the Illumina tool fails with the following error message:
```
Failed to normalize and gencall sample: GSM5902662_203182650277_R07C01, it will be skipped. Error: Normalization failed for sample: GSM5902662_203182650277_R07C01. Error: Index was outside the bounds of the array.
```
The problem is that you are using the wrong manifest file. If you run the `bcftools +gtc2vcf -i ../resources/downloads/test//GSM5902662_203182650277_R07C01_Grn.idat` command you should get in the output:
```
Chip Prefix (Guess),GSAMD-24v2-0_20024620
```
If you have manifest and cluster files for this custom chip you can use those. Alternatively, you can use the manifest and cluster files from the [GSA-24v2-0](https://support.illumina.com/downloads/infinium-global-screening-array-v2-0-product-files.html) array, though doing so will make you lose all the custom variants

In the next version of the plugin I will add a check for this type of situations and suggest that most likely the wrong manifest file was used

**Comment by Dazcam** [comment]
@freeseek Many thanks, again, for looking into this. Everything is now running as expected with the new manifest and cluster files.
