### ISSUE TITLE
Multi allelic records

### ISSUE THREAD

**Issue by rajwanir** [freeseek/gtc2vcf#71]
Hi @freeseek 

May I please clarify on how multi-allelic records are represented in the gtc2vcf output? Per the documentation, I understand that it writes individual probes as is without attempting to merge the records for the same position or pos+alt. However, I find it a bit confusing on interpreting the genotypes for the multi-allelic records.

For example, for a sample I see:

> chr16 16198126 rs9930886.1 A C 0/1
> chr16 16198126 16:16291983 A G 0/1
> chr16 16198126 rs9930886.2 A G 0/1

I checked Illumina's Dragen Array gtc-to-vcf and it attempts to merge by default and writes the record as:

> 16 16198126 16:16291983,rs9930886.1,rs9930886.2 A G,C 0/1

The genotypes are inconsistent between the above two. Based on gtc2vcf ouput, I am guessing that the sample probably has the  `C` and `G` allele at `chr16:16198126` so the bi-alllelic verion might be better represented with partial missing genotypes :

> chr16 16198126 rs9930886.1 A C ./1
> chr16 16198126 16:16291983 A G ./1
> chr16 16198126 rs9930886.2 A G ./1

I have additional similar records that I see from the GSA chip. I wanted see what your thoughts are on this.

Thanks again for this excellent tool.

**Comment by freeseek** [comment]
It is not immediate to tell you what the correct genotype is. What you would know is that the probes intensities for the three pairs genotyped as heterozygous. There is not much more information to that in the array intensities. The interpretation can be based on many other pieces of data. As an example, the same pair of probes could be genotyping a SNP or an indel, but it is your prior on what should be polymorphic that allows you to guess correctly what is being genotyped. In this case gtc2vcf only converts the data from GTC to VCF and all three markers are marked as heterozygous in the GTC file. To know the most likely genotype you should look into something like the 1000 Genome project and figure out which two alleles are the most common alleles for the site. Most likely your sample has one each of the two most common alleles

**Comment by rajwanir** [comment]
Makes sense if the genotypes could not be fully resolved based on array data alone in this context.

Does this mean that the heterozygous genotypes from gtc2vcf output (e.g. `0/1`) can not be interpreted as having one `REF` allele and another `ALT`? It can only be interpreted that the site is heterozygous? Does this apply to all records including simple biallelic records queried by a single probe? 

What about homozygous sites? safe to interpret `0/0` as homozygous reference and `1/1` as homozygous alt.

Sorry for the naive questions.

**Comment by freeseek** [comment]
For most probes there is no confusion. The problem arises where you have probes designed for alleles that are either not-existing or very rare and the site is more than bi-allelic. Suppose you have three possible alleles. Each probe will hybridize with different intensity for each allele (and genotype combination). However the GenCall algorithm will only cluster allowing for two alleles (and three genotypes), so you will only cluster for the two most common alleles. If you really think all three alleles are common, maybe try to plot the probe intensities with gtc2vcf_plot.R and that may give you some clues. I would actually advise you to try it just to get a better feeling for what the raw data looks like. It will help you to come up with the answers on your own

**Comment by rajwanir** [comment]
Thanks @freeseek. Appreciate the info.
