### ISSUE TITLE
Indel left-normalized within gtc2vcf by default? Options to turn this off?

### ISSUE THREAD

**Issue by rajwanir** [freeseek/gtc2vcf#73]
Hello @freeseek ,

Are indels left-shifted within gtc2vcf by default?  If that is the case, is there any possibility to add a switch to override this and skip left-shifting the indels? I was under the impression that left-normalization is handled in a subsequent pipe to bcftools norm as shown in the documentation but it appears that gtc2vcf itself shifts the indels to left. This results in incorrect coordinates if the csv_manifest already contains correct and left-aligned positions (e.g. one prepared with SourceSeq mapping or a user wants to keep the orignal Illumina coordinate regardless). 

A few example CSV manifest records as input (ID,CHROM,POS) :

> rs797044834,1,1338099
rs797044836,1,1338108

The output VCF records from gtc2vcf ((ID CHROM POS):

> rs797044834 chr1 1338098
rs797044836 chr1 1338107

I am using the following flags to run gtc2vcf:

`bcftools +gtc2vcf   --bpm $bpm_manifest --csv $csv_manifest   --egt $cluster_file   --gtcs dc/gtcs  --fasta-ref $ref_genome `
 
Is there any parameter combination that will currently override left-shifting indels?

Thank you

**Comment by rajwanir** [comment]
I see. Thanks for the info and prompt response @freeseek .  

To confirm once, the csv_manifest input to the gtc2vcf follow the [implicit dbSNP standard](https://github.com/Illumina/GTCtoVCF#manifests) (i.e. deletion position represented as last base deleted). Even csv_manifest the from SourceSeq mapping workflow follows the same  implicit dbSNP standard consistent with a Illumina's CSV manifest specification. On the other hand, the output VCF records follow the standard VCF representation (i.e. deletion position represented as one bp before the last deleted base)?

I was actually trying to compare the output VCF records from gtc2vcf to dbSNP VCF and noted that the indel coordinates do not match. Probably for the reason you mentioned that indels in gtc2vcf and dbSNP vcf follow a different standard. Do you have suggestions preferably within BCFtools functions to bring them to the same representation? Or simply just subtract one from the deletion positions in the csv manifest but it seems a bit crude solution.

Thanks.

**Comment by freeseek** [comment]
```
$ wget ftp://ftp.ncbi.nlm.nih.gov/snp/redesign/latest_release/VCF/GCF_000001405.40.gz{,.tbi}
$ bcftools view -Hr NC_000001.11:1338098,NC_000001.11:1338108 GCF_000001405.40.gz | grep "rs797044834\|rs797044836"
NC_000001.11	1338098	rs797044834	GGGGGCAGCCGGGT	G	.	.	RS=797044834;dbSNPBuildID=146;SSR=0;GENEINFO=DVL1:1855;VC=INDEL;PUB;NSF;CLNVI=.,OMIM:601365.0001;CLNORIGIN=.,5;CLNSIG=.,5;CLNDISDB=.,GeneReviews:NBK268648/MONDO:MONDO:0014591/MedGen:C4225363/Orphanet:3107/Orphanet:97360/OMIM:616331;CLNDN=.,Autosomal_dominant_Robinow_syndrome_2;CLNREVSTAT=.,single;CLNACC=.,RCV000193850.4;CLNHGVS=NC_000001.11:g.1338099_1338119=,NC_000001.11:g.1338107_1338119del
NC_000001.11	1338107	rs797044836	CG	C	.	.	RS=797044836;dbSNPBuildID=146;SSR=0;GENEINFO=DVL1:1855;VC=INDEL;PUB;NSF;CLNVI=.,OMIM:601365.0003;CLNORIGIN=.,5;CLNSIG=.,5;CLNDISDB=.,GeneReviews:NBK268648/MONDO:MONDO:0014591/MedGen:C4225363/Orphanet:3107/Orphanet:97360/OMIM:616331;CLNDN=.,Autosomal_dominant_Robinow_syndrome_2;CLNREVSTAT=.,single;CLNACC=.,RCV000192930.3;CLNHGVS=NC_000001.11:g.1338108_1338110=,NC_000001.11:g.1338110del
```
the dbSNP VCF coordinates match the VCF coordiantes from gtc2vcf, that is 1,338,098 and 1,338,107, as they should. There is no discrepancy. If you look at dbSNP non-VCF coordinates for [rs797044834](http://www.ncbi.nlm.nih.gov/snp/rs797044834) and [rs797044836](http://www.ncbi.nlm.nih.gov/snp/rs797044836) instead, you match the Illumina manifest file coordinates, that is, 1,338,099 and 1,338,108

**Comment by rajwanir** [comment]
It was my bad. Overlooked a couple things most importantly that dbSNP vcf have the accession numbers in the Chrom field and not the USC style chromosome ids so `bcftools intersect`  flagging all as different. Also was switching between comparing dbSNP vcf and dbSNP web version for comparision without realizing that variant representation is different both formats as you explained above.

Thank you.
