### ISSUE TITLE
Any way to access Illumina's support ftp?

### ISSUE THREAD

**Issue by teepean** [freeseek/gtc2vcf#79]
Does anyone know current login and password to Illumina's ftp? For example these files are currently not accessible and I need them for a project.

https://emea.support.illumina.com/downloads/human660w-quad_v10_product_files.html

iaap-cli is also hosted at the same site and it also complains about wrong password.

wget ftp://webdata2:webdata2@ftp.illumina.com/downloads/software/iaap/iaap-cli-linux-x64-1.1.0.tar.gz

**Comment by freeseek** [comment]
It seems like `ftp://webdata2:webdata2@ftp.illumina.com` is not working anymore while `ftp://webdata:webdata@ftp.illumina.com` is still working. The files you are looking for are still available though:
```
wget ftp://webdata:webdata@ftp.illumina.com/Public_Docs/Whole%20Genome%20Genotyping%20Files/Archived_Human_Products/Human660W-Quad_v1_H_product_files/Product%20Files/Human660W-Quad_v1_H_bpm.zip
wget ftp://webdata:webdata@ftp.illumina.com/Public_Docs/Whole%20Genome%20Genotyping%20Files/Archived_Human_Products/Human660W-Quad_v1_H_product_files/Product%20Files/Human660W-Quad_v1_H_egt.zip
wget ftp://webdata:webdata@ftp.illumina.com/Public_Docs/Whole%20Genome%20Genotyping%20Files/Archived_Human_Products/Human660W-Quad_v1_H_product_files/Support%20Files/Human660W-Quad_v1_H_csv.zip
```
Why do you need iaap-cli? You can use BCFtools/idat2gtc with option `--preset 3` to emulate iaap-cli behavior (minus a gender inference bug present in iaap-cli)

**Comment by teepean** [comment]
Thank you! I don't need iaap-cli but is on the front page of gtc2vcf as part of the instructions.

Do you know if these are available as well?

https://emea.support.illumina.com/downloads/human610-quad_v10_product_files.html

**Comment by freeseek** [comment]
```
wget ftp://webdata:webdata@ftp.illumina.com/Public_Docs/Whole%20Genome%20Genotyping%20Files/Archived_Human_Products/Human610-Quad_v1_product_files/Human610-Quadv1_C.bpm
wget ftp://webdata:webdata@ftp.illumina.com/Public_Docs/Whole%20Genome%20Genotyping%20Files/Archived_Human_Products/Human610-Quad_v1_product_files/Human610-Quadv1_C.egt
wget ftp://webdata:webdata@ftp.illumina.com/Public_Docs/Whole%20Genome%20Genotyping%20Files/Archived_Human_Products/Human610-Quad_v1_product_files/Human610-Quadv1_C.csv
```
As for iaap-cli, it is at the very end of the gtc2vcf documentation. It is only provided for comparison purposes and to check that BCFtools/idat2gtc performs as intended

**Comment by teepean** [comment]
Thank you!
