### ISSUE TITLE
How to install wine64 without "sudo"?

### ISSUE THREAD

**Issue by vbruat** [freeseek/gtc2vcf#9]
Hi,

Can you tell me if there is a way to install wine64 not using the sudo command. I don't have the right to use sudo on the cluster that I use.

Thanks.

**Comment by vbruat** [comment]
Finally I have already "wine" on the cluster.

**Comment by freeseek** [comment]
An alternative would be to install AutoConvert using your own Linux machine or your own Windows machine. Then you can copy the corresponding AutoConvert directory to your Linux cluster. Notice that Illumina recently made available an alternative framework: https://support.illumina.com/downloads/iaap-genotyping-cli.html which should allow you to convert IDATs to GTCs natively on Linux without .NET emulation. Last time I checked it was not working with RHEL6 or RHEL7 though.
